#!/bin/bash
if [ ! -d "bin" ]; then
  mkdir bin
fi

javac -d bin $(find src -name *.java)


if [ $? ]; then
  echo "Successfully compiled. Creating JAR executable."
  jar cmvf META-INF/MANIFEST.MF Chess.jar bin
  if [ $? ]; then
    echo "Done"
  else
    echo "Error while creating JAR file, try again."
  fi
else
  echo "Error during compiling! Try re-downloading and try again."
fi
